// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return the signed-in MathClair student or parent profile (name, level, school, language).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sbForUser(ctx).from("profiles").select("name, level, school, lang, is_parent, child_name").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/get-progress.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_progress_default = defineTool2({
  name: "get_progress",
  title: "Get study progress",
  description: "Return per-topic practice progress and recent study sessions for the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser2(ctx);
    const uid = ctx.getUserId();
    const [progress, sessions] = await Promise.all([
      sb.from("user_progress").select("topic, exercises_done, exercises_correct, last_practiced").eq("user_id", uid).order("last_practiced", { ascending: false }),
      sb.from("study_sessions").select("date, minutes_studied, exercises_attempted, exercises_correct").eq("user_id", uid).order("date", { ascending: false }).limit(14)
    ]);
    if (progress.error) return { content: [{ type: "text", text: progress.error.message }], isError: true };
    if (sessions.error) return { content: [{ type: "text", text: sessions.error.message }], isError: true };
    const payload = { topics: progress.data ?? [], recent_sessions: sessions.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/log-study-session.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var log_study_session_default = defineTool3({
  name: "log_study_session",
  title: "Log a study session",
  description: "Record a MathClair study session (minutes studied and exercise counts) for the signed-in user.",
  inputSchema: {
    minutes_studied: z.number().int().min(0).max(600).describe("Minutes studied in this session."),
    exercises_attempted: z.number().int().min(0).max(1e3).default(0).describe("Number of exercises attempted."),
    exercises_correct: z.number().int().min(0).max(1e3).default(0).describe("Number of exercises answered correctly."),
    date: z.string().optional().describe("ISO date (YYYY-MM-DD). Defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const row = {
      user_id: ctx.getUserId(),
      minutes_studied: input.minutes_studied,
      exercises_attempted: input.exercises_attempted,
      exercises_correct: input.exercises_correct,
      ...input.date ? { date: input.date } : {}
    };
    const { data, error } = await sbForUser3(ctx).from("study_sessions").insert(row).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Logged study session on ${data.date}.` }],
      structuredContent: { session: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lsiknhkchryvkfisezik";
var mcp_default = defineMcp({
  name: "mathclair-mcp",
  title: "MathClair MCP",
  version: "0.1.0",
  instructions: "Tools for MathClair \u2014 a bilingual (English/French) math tutor for Cameroon students. Use `get_profile` to fetch the signed-in user's profile, `get_progress` to review per-topic progress and recent study sessions, and `log_study_session` to record time spent and exercises completed.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, get_progress_default, log_study_session_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
